### ISSUE TITLE
Repeating fields in subcomponents?

### ISSUE THREAD

**Issue by tremby** [verbb/vizy#126]
Please forgive me and educate me if I'm missing something obvious! We'd ploughed ahead assuming this feature exists but now I'm not so sure.

**What are you trying to do?**
Offer subcomponents such as riverflows or card grids, which need to support an arbitrary number of repeating groups of fields.

**What's your proposed solution?**
Allow repeating fields or repeating groups of fields in Vizy subcomponent blocks.

**Additional context**
I'm aware that this is technically complex. But I'd call it absolutely vital if Vizy is intended for use as a replacement for things like Matrix and Neo.

**Comment by engram-design** [comment]
Because Vizy Blocks just house regular Craft fields, we rely on Craft fields to do heavy lifting such as this, and that'll probably always be the case. You'd be looking at Matrix, Neo or Super Table.

But in terms of offering these "types" of nodes, that's something we're certainly considering with layout-style nodes, but as you've stated adding in repeatable functionality adds complexity from a UI point of view, so we'd want to ensure that's a good experience and can be managed well.

And Vizy isn't looking to be a replacement for these fields, but a companion alongside them, so you can more easily integrate WYSIWYG content with regular Craft fields, and more control over templating.

If you've seen anything in the wild that's similar to what you're thinking, would love to see!

**Comment by tremby** [comment]
So if I wanted to mix wysiwygs with complex components, do you see that working as an all-encompassing Neo or similar, which allows an abitrary number of blocks to be added: maybe a Vizy, then some kind of card grid which has child blocks of its own, another Vizy...?

Or are you saying there's a way using Neo or similar to drop such complex fields into Vizy blocks?

I tried just now to drop my SEOmatic field (other than Vizy that's the most complicated thing I have so far) in to a Vizy block definition, and this appears to work fine -- it expands out to some 5 other fields. Could I drop a Neo or something in, in the same way, to get the behaviour I'm looking for?

(I'm pretty new to Craft, in case that wasn't obvious, and I'm not yet totally clear on how the different plugins mesh with each other!)

**Comment by engram-design** [comment]
It depends how you want to do it, but I would recommend creating a "Cards" Vizy blocktype, and in that blocktype add a Super Table field called "Cards". This would have an image, title, text, link field, which would be repeatable. You could of course use Matrix or Neo for the same field, but Super Table acts on the preface that there's only a single blocktype, and a "Cards" field would be single-purpose.

Then, in the entry, you create your "Cards" Vizy Block, and inside that, create repeatable Super Table blocks for your cards.

And that's exactly right (your SEOmatic comment) - you can drop **any** field into a Vizy blocktype, so as per the above, you could use Matrix or Neo in a Vizy block to get the repeatable content you need

**Comment by tremby** [comment]
Thanks so much for your input.

**Comment by engram-design** [comment]
Closing this to track in https://github.com/verbb/vizy/issues/72 where we'll be adding different types of nodes for layout among other things.
