### ISSUE TITLE
Craft 4 - Codemiror - vizy

### ISSUE THREAD

**Issue by wmdhosting** [verbb/vizy#182]
### Describe the bug

Seems some issue With CodeMiror and Vizy 
when  i use vizy field   

Drafts cant be saved,.. 
and craft  category / asset modal is not working

here is error. 
![Snag_ca6fa29](https://user-images.githubusercontent.com/76176291/197820495-08674ca2-47bc-4b15-9b73-b9235eccd70c.png)

When i remove vizy field.  .. it work ok.. 

### Steps to reproduce

1. add https://dev-korisnik.wmd.hr/admin/plugin-store/code-mirror  to some filed globals .or anywhere
2. add vizy field  in section..

Drafts cant be saved.. 
Craft Modal .. just loading. .never finish..

### Craft CMS version

4.2.8

### Plugin version

2.0.8 

### Multi-site?

Y

**Comment by engram-design** [comment]
Not sure what we can do about that, these two plugins are incompatible with each other due to how they load CodeMirror, but I'm pretty sure it's down to the fact they load two different versions of CodeMirror, but Vizy tries to load the already-loaded CodeMirror library (through the `vue-codemirror` library).

To get around this, I would add the missing `mode/simple` addon in your `code-mirror.php` plugin settings.

```php
return [
    'addons' => [
        'mode/overlay',
        'mode/simple',
    ]
];
```
