### ISSUE TITLE
Link to asset

### ISSUE THREAD

**Issue by JshGrn** [verbb/vizy#220]
### What are you trying to do?

Being able to link to an Asset directly such as a PDF within the editor

### What's your proposed solution?

Adding 'Link to asset' under 'Link to entry' on the 'Link' button

### Additional context

Can link to Entry but cannot link directly to asset, example for this would be in Wordpress *shudders*, you can hyperlink some text to a PDF, this is pretty much the usecase I have and cannot see how I can do this.

Additionally, I cannot see how to make the link open in a new window/tab... target="_blank"?

**Comment by engram-design** [comment]
What version of Vizy are you on? There was a bug preventing linking to an asset, which was fixed in [2.1.1](https://github.com/verbb/vizy/blob/craft-4/CHANGELOG.md#211---2023-04-19).

As for setting links to open in a new window, that's an option once you select the element 
<img width="661" alt="image" src="https://user-images.githubusercontent.com/1221575/235000417-d6cacfa5-4bd0-4d2e-a0e5-7ebd728344da.png">

**Comment by JshGrn** [comment]
2.1.3, I only see link to entry, not asset, maybe I've configured it wrong somewhere?

**Comment by JshGrn** [comment]
After you pointing this out to me, I had not selected any available asset locations on the Vizy field itself. Rookie mistake...
