### ISSUE TITLE
Adding a ColorIt field to a Vizy block prevents any other fields in that block from rendering

### ISSUE THREAD

**Issue by Michael-Paragonn** [verbb/vizy#244]
### Describe the bug

Adding a ColorIt field to a Vizy block prevents any of the fields belonging to that block from showing; the block itself is collapsed down to a few pixels:

![image](https://github.com/verbb/vizy/assets/118922451/689e1502-3e85-49f2-94a3-6bd0f2038541)

In the image, the "Embed Code" block has a Colorit field in the Design tab:

![image](https://github.com/verbb/vizy/assets/118922451/ebc6c69c-b3f5-41c9-9ff2-2c65151f7507)

The "Text" field has a native Craft color field in the Design tab:

![image](https://github.com/verbb/vizy/assets/118922451/673264c6-ceee-455c-a630-e29a3048ada3)

### Steps to reproduce

1. Create a Vizy field, and some blocks.
2. Add a Colorit field to a block.

### Craft CMS version

Craft Pro 4.4.16.1

### Plugin version

2.1.6

### Multi-site?

No

### Additional context

All plugins:
- Batch Actions 1.3.0
- Button Box 4.2.0
- Cloudflare 2.0.0
- Colorit 4.0.0
- Color Mixer 3.0.0
- Cookies 4.0.0
- CP Field Inspect 1.4.4
- Field Manager 3.0.6
- Freeform 4.1.6
- Icon Picker 2.0.13
- Inventory 3.1.0
- LJ Range Slider 4.0.1
- Navigation 2.0.18
- Neo 3.7.9
- oEmbed 2.3.0
- Postmark 3.0.0
- Redactor 3.0.4
- Retour 4.1.12
- SEOmatic 4.0.30
- Sidebar Entry Types 2.0.1
- Social Share 1.0.1
- Sprig 2.6.2
- Super Table 3.0.9
- Twigpack 4.0.0-beta.4
- Typed link field 2.1.5
- Vizy 2.1.6

**Comment by engram-design** [comment]
This is because the [ColorIt](https://github.com/presseddigital/colorit/tree/v4) plugin includes invalid HTML (to Vue at least) where there are duplicate attributes of the `data-color`.

<img width="1054" alt="image" src="https://github.com/verbb/vizy/assets/1221575/8e90b894-61c2-444b-b9ed-9940f5c4c075">


Reference [here](https://github.com/presseddigital/colorit/blob/121d77b584c4de770f929192f17463be3a2eca7b/src/templates/_fields/colorit/input.twig#L28).

It'll need to be fixed there.

**Comment by Michael-Paragonn** [comment]
Ok, thanks, Josh!
