### ISSUE TITLE
Duplicate names or handles creates issue

### ISSUE THREAD

**Issue by letisanchez** [verbb/vizy#40]
**Description**
If you use the same handle for the field, as well as for the vizy group block handle, it will not output the content. Doesn't give any kind of error either, just leaves the section blank on the browser for that particular item.

**Steps to reproduce**
1. Create 'Heading' field with handle 'heading'.
2. Create Vizy field.
3. In vizy field, add a group labeled the same as the field created in step 1. Group name: Heading, block name: "Heading", handle: heading.
4. Assign your template and save.
5. Use `<h1>{{ heading }}</h1>` on twig template file.
6. Check browser - it outputs nothing for the heading.

**Additional info**
- Plugin version: 1.0.2
- Craft version: 3.6.15
- Multi-site: No

**Additional context**
I repeatedly changed the names between the heading field and the heading group in the vizy field. Changing the group name to 'headline text' seems to have fixed the issue, or a combination of altering the field names. Couldn't find anything in the documentation that mentioned having to use a unique name from the field, but something to maybe include in the documentation?

**Comment by engram-design** [comment]
There shouldn't be any sort of restrictions like that, so that seems quite odd.

Here's my setup which is working. Let me know if I've missed anything from your setup.

![image](https://user-images.githubusercontent.com/1221575/122071503-1f17a380-ce3a-11eb-8d08-af12e9faeb97.png)

![image](https://user-images.githubusercontent.com/1221575/122071591-348ccd80-ce3a-11eb-8b47-2283290b78cb.png)

![image](https://user-images.githubusercontent.com/1221575/122071628-3ce50880-ce3a-11eb-85f6-14fe7d25bd18.png)

_entry.html
```
<p><strong>{{ entry.type.name }}</strong></p>

{{ entry.vizyHeading.renderHtml() }}
```

_blocks/heading.html
```
<h1>{{ heading }}</h1>
```
